### PR TITLE
Fix #106: Fix wrongly filtered out packages when using --versioned-dirs

### LINKED ISSUE #106: New flag --versioned-dirs doesn't work
Urgh, my latest PR adding the flag `--versioned-dirs` is unfortunately buggy. 
The versioned dirs get filtered out by default, if there is only one version in the tree, as the dirname-heuristic is at odds with it and thinks this is an unreferenced package.
Looking into properly fixing this now (and maybe using `--versioned-dirs` as a default)

### PR DESCRIPTION
**Pull request by msirringhaus**
I have not (yet) made `--versioned-dirs` the default, as I think we might want to have a separate discussion about this.

As I'm not clear on the following question:
Once it's the default, should `--versioned-dirs` be a no-op flag, or should the user still be able to DEactivate that feature? Depending on the answer, we can or can't remove the decision-code I added.

### CODE REVIEW

File: tests/vendor_filterer/common.rs [hunk 1]
```diff
@@ -168,3 +168,22 @@ pub(crate) fn verify_no_macos(dir: &Utf8Path) {
...
+
+pub(crate) fn verify_crate_is_no_stub(output_folder: &Utf8Path, name: &str) {
+    let crate_dir = output_folder.join(name);
+    assert!(
+        crate_dir.exists(),
+        "Package does not show up in the vendor dir"
+    );
+    let crate_lib = crate_dir.join("src/lib.rs");
+    assert!(
+        crate_lib.exists(),
```
Comment (cgwalters) [inline tests/vendor_filterer/common.rs:180]: We really want to check it has nonzero size; stub crates *do* have a `lib.rs` that's zero size. I guess this was a bug in the original code.

File: src/main.rs [hunk 2]
```diff
@@ -897,13 +897,16 @@ fn run() -> Result<()> {
     for (_name, mut pkgs) in pkgs_by_name {
         // Reverse sort - greater version is lower index
         pkgs.sort_by(|a, b| b.version.cmp(&a.version));
-        // SAFETY: The package set must be non-empty
-        let (first, rest) = pkgs.split_first().unwrap();
-
-        if packages.contains_key(&first.id) {
-            package_filenames.insert(Cow::Borrowed(first.name.as_str()), *first);
+        // If we use versioned-dirs, we insert all packages with a versioned filename
```
Comment (cgwalters) [inline src/main.rs:900]: Ah yes...I should have double checked this. It's not surprising this logic needed to change.

File: src/main.rs [hunk 3]
```diff
@@ -897,13 +897,16 @@ fn run() -> Result<()> {
...
+        // If not, we split off the first package and insert it without a version-suffix
+        if !args.versioned_dirs {
+            // SAFETY: The package set must be non-empty
+            let (first, _rest) = pkgs.split_first().unwrap();
+            if packages.contains_key(&first.id) {
+                package_filenames.insert(Cow::Borrowed(first.name.as_str()), *first);
+            }
         }
-        for &pkg in rest {
+        for pkg in &pkgs {
```
Comment (cgwalters) [inline src/main.rs:909]: Hmm but aren't we going to insert a duplicate of the first one now? I guess it doesn't matter...but feels a bit unclean.

Probably what we want to is something like:

```
let versioned_pkgs;
if !args.versioned_dirs {
    let (first, rest) = pkgs.split_first().unwrap();
    versioned_pkgs = Either::Left(rest.iter());
    ...
} else {
    versioned_pkgs = Either::Right(pkgs.iter());
}
for pkg in versioned_pkgs {
...
```
or so?

**Comment by cgwalters** [comment]
> I have not (yet) made --versioned-dirs the default, as I think we might want to have a separate discussion about this.

Yeah agree.

File: src/main.rs (hunk 3 above)
Comment (msirringhaus) [reply src/main.rs:909]: Oh, right. I thought `split_first()` modifies `pkgs`.

File: tests/vendor_filterer/common.rs (hunk 1 above)
Comment (msirringhaus) [reply tests/vendor_filterer/common.rs:180]: We are doing `assert_ne!()` (not equal) on the zero-length :)

File: src/main.rs (hunk 3 above)
Comment (msirringhaus) [reply src/main.rs]: Done

**Review by cgwalters — APPROVED** [review]
